SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE SCHEMA IF NOT EXISTS supplies;

SET default_tablespace = '';

CREATE TABLE supplies.supplies (
    id bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    is_valid boolean,
    manager_code bigint NOT NULL,
    model_version character varying(20),
    municipality_code character varying(10) NOT NULL,
    name character varying(500),
    observations character varying(500),
    request_code bigint,
    type_supply_code bigint,
    state_id bigint NOT NULL
);

CREATE TABLE supplies.supplies_attachments (
    id bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    data character varying(2000) NOT NULL,
    attachment_type_id bigint NOT NULL,
    supply_id bigint NOT NULL
);

ALTER TABLE supplies.supplies_attachments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME supplies.supplies_attachments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE supplies.supplies_attachments_types (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);

ALTER TABLE supplies.supplies_attachments_types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME supplies.supplies_attachments_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE supplies.supplies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME supplies.supplies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE supplies.supplies_owners (
    id bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    owner_code bigint NOT NULL,
    owner_type character varying(50) NOT NULL,
    supply_id bigint NOT NULL
);

ALTER TABLE supplies.supplies_owners ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME supplies.supplies_owners_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE supplies.supplies_states (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);

ALTER TABLE supplies.supplies_states ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME supplies.supplies_states_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

INSERT INTO supplies.supplies_attachments_types VALUES (1, 'ARCHIVO');
INSERT INTO supplies.supplies_attachments_types VALUES (2, 'FTP');
INSERT INTO supplies.supplies_attachments_types VALUES (3, 'ENTREGA FÍSICA');

INSERT INTO supplies.supplies_states VALUES (1, 'ACTIVO');
INSERT INTO supplies.supplies_states VALUES (2, 'INACTIVO');
INSERT INTO supplies.supplies_states VALUES (3, 'ELIMINADO');

SELECT pg_catalog.setval('supplies.supplies_attachments_id_seq', 1, false);
SELECT pg_catalog.setval('supplies.supplies_attachments_types_id_seq', 3, true);
SELECT pg_catalog.setval('supplies.supplies_id_seq', 1, false);
SELECT pg_catalog.setval('supplies.supplies_owners_id_seq', 1, false);
SELECT pg_catalog.setval('supplies.supplies_states_id_seq', 3, true);

ALTER TABLE ONLY supplies.supplies_attachments
    ADD CONSTRAINT supplies_attachments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY supplies.supplies_attachments_types
    ADD CONSTRAINT supplies_attachments_types_pkey PRIMARY KEY (id);

ALTER TABLE ONLY supplies.supplies_owners
    ADD CONSTRAINT supplies_owners_pkey PRIMARY KEY (id);

ALTER TABLE ONLY supplies.supplies
    ADD CONSTRAINT supplies_pkey PRIMARY KEY (id);

ALTER TABLE ONLY supplies.supplies_states
    ADD CONSTRAINT supplies_states_pkey PRIMARY KEY (id);

ALTER TABLE ONLY supplies.supplies
    ADD CONSTRAINT fkcqnuux9mukugkg2pphv2tl2xq FOREIGN KEY (state_id) REFERENCES supplies.supplies_states(id);

ALTER TABLE ONLY supplies.supplies_owners
    ADD CONSTRAINT fkji8m8lptgn5lodrtes5da1j15 FOREIGN KEY (supply_id) REFERENCES supplies.supplies(id);

ALTER TABLE ONLY supplies.supplies_attachments
    ADD CONSTRAINT fkqklh4hs350kjghiawxeh9t2s8 FOREIGN KEY (supply_id) REFERENCES supplies.supplies(id);

ALTER TABLE ONLY supplies.supplies_attachments
    ADD CONSTRAINT fks1yol7abrd26ekjh5oca1dr72 FOREIGN KEY (attachment_type_id) REFERENCES supplies.supplies_attachments_types(id);